language: swift
osx_image: xcode13.2
env:
  global:
  - FRAMEWORK_NAME=AWSAppSync
xcode_workspace: AWSAppSyncClient.xcworkspace
xcode_scheme: AWSAppSync
before_install:
- openssl aes-256-cbc -K $encrypted_6919a533707f_key -iv $encrypted_6919a533707f_iv
  -in AWSAppSyncIntegrationTests/appsync_test_credentials.json.enc
  -out AWSAppSyncIntegrationTests/appsync_test_credentials.json
  -d
- brew update
- brew outdated carthage || brew upgrade carthage
- gem install cocoapods -v '1.9.3'
before_deploy:
- bash ./build-support/carthage-build.sh build --no-skip-current
- bash ./build-support/carthage-build.sh archive $FRAMEWORK_NAME
script:
- xcodebuild -quiet -workspace AWSAppSyncClient.xcworkspace -scheme AWSAppSync build test -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest'
deploy:
- provider: releases
  api_key:
    secure: "Av3upz4HUWlKiReRrpKtyHbn/k3hKXJydGEp+P08i6NheWrjZsgLkm9CbmdWoomwgKFmSmqCEaqy5+gnjQ+vO9k6PIFZXMk4UjW9ZrbpTeR6XZmsRYGFbkSVJViEzbK/Bkrve/ZLA/XwAyva8vuX/0qtOeudQFjcbcUulaKDMqKewrsTtfGot8eiYkhyf8HVZd+vXMm3+dY6GL01WJ/Vyy2T8r4AGqsPjVLr4nclLcYK0UMfLJaHb3JQmliF9MmIKNqW0nOqh+oMdoH1HOd5Oe3YghAfRqfk6lnYmjkCi+EKl9/VU6q6IuRQI6OzLf5EJB2IIFHsjQdscdcvnsESy57aRW/bx1OegaDlI0+RkwR2i4ewoFkrpk0bAUDHQFdvfqaMgbszNgzWhgB3n2w+1T3G6GZ7hBQYecTyatKt8j4ZfKqNZ1OXdL2Wh/2VC64y/GK57hYy5iDWnv6hIJEljV0nUGR2Vh5MslSkdqEsicfFH5ugYEBUBYn/MSLhxHABRIyEbH9YH9uXQ7yOvmqU3nWcdWC4yHf211xa4A7ztXLv6qblzWbH0DAbwLScvdVucp1qf95wVGKI4dm775iWmybVlLZpKuFY4hkc3oHCF0cA+2L+3GOYsgP0Cm67LQHzguP7+URAZ70DZ4M/PXD3oTbTJEw2l2Q2N8qjz7KYk2o="
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
   repo: awslabs/aws-mobile-appsync-sdk-ios
   tags: true
- provider: script
  script: bash ./build-support/cocoapods_release.sh
  on:
    repo: awslabs/aws-mobile-appsync-sdk-ios
    tags: true
